{% set version = "2023.5.1" %}

package:
  name: jsonschema-specifications
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jsonschema-specifications/jsonschema_specifications-{{ version }}.tar.gz
  sha256: ca4c182adb268045fb70e6c09eb818ff4f9d27e762725b0f257cfdd318dffca9

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - hatch-vcs
    - hatchling
    - pip
    - python >=3.8
  run:
    - importlib_resources >=1.4.0
    - python >=3.8
    - referencing >=0.25.0

test:
  imports:
    - jsonschema_specifications
  commands:
    - pip check
    - pytest -vv --pyargs jsonschema_specifications --cov-branch --cov=jsonschema_specifications --cov-report=term-missing:skip-covered --no-cov-on-fail --cov-fail-under=88
  requires:
    - pip
    - pytest
    - pytest-cov

about:
  summary: The JSON Schema meta-schemas and vocabularies, exposed as a Registry
  home: https://github.com/python-jsonschema/jsonschema-specifications
  license: MIT
  license_file: COPYING
  doc_url: https://jsonschema-specifications.readthedocs.io

extra:
  recipe-maintainers:
    - bollwyvl
